platform :ios, '7.0'
pod 'AFNetworking', '>=2.3.1'
pod 'Reachability', '>=3.1.1'
pod 'SVProgressHUD', '>=1.0'

pod 'FBSDKCoreKit', '~> 4.10'
pod 'FBSDKLoginKit', '~> 4.10'
pod 'FBSDKShareKit', '~> 4.10'

pod 'TwitterKit', '~> 1.15'
#pod 'NIDropDown', '~> 0.1'
pod 'TPKeyboardAvoiding', '~> 1.2'

#target 'StingWax Tests', :exclusive => true do
#  pod 'OCHamcrest'
#  pod 'OCMock'
#  pod 'OHHTTPStubs'
#  pod 'Nocilla'
#end